### ISSUE TITLE
Update app title and add header.  

### ISSUE THREAD

**Issue by Kedevlin** [Kedevlin/BreakProject#12]
Currently app is called Break Project.  Would like to change this to "Seattle on the Cheap" (or something else if you have a good idea for a title).  Then add a header so that each page displays the app title.

**Comment by loganmeetsworld** [comment]
I can do this. Are you using a CSS framework?

**Comment by Kedevlin** [comment]
Great, thank you! I did not use a CSS framework, but @Dreedle is working on issue #11 and may be adding Bootstrap?

**Comment by Dreedle** [comment]
I just opened a pr in case you want to merge so that Logan can get a version that has the js, scss, gems etc added to make it bootstrap-ready. If that's not what you want to do just ignore or close the pr and I'll open another when I finish working.

**Comment by Kedevlin** [comment]
Cool, I merged @Dreedle 's pr.  Thanks all!

**Comment by loganmeetsworld** [comment]
@Kedevlin cool! I'll work on it today.

**Comment by loganmeetsworld** [comment]
@Kedevlin I added a title, header with the title and a new font for the title. I'll PR now.
